/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lee_delpath_JniTools */

#ifndef _Included_com_lee_delpath_JniTools
#define _Included_com_lee_delpath_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lee_delpath_JniTools
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lee_delpath_JniTools_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_lee_delpath_JniTools
 * Method:    removePath
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lee_delpath_JniTools_removePath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
